### ISSUE TITLE
[Bug]: After starting for a while under macOS, no available windows can be found when switching windows

### ISSUE THREAD

**Issue by normal-coder** [lisiur/ChatWizard#59] opened 2023-07-28 14:18 UTC
### Describe the bug

After starting for a while under macOS, no available windows can be found when switching windows

### Steps to Reproduce

1. Launch ChatWizard on macOS.
2. After using it for a while (maybe switching to other applications), switch back to ChatWizard, there is no valid window to switch.
3. Confirm that the "hide main window" setting is not turned on

### Expected behavior

The window can be switched normally, and the window will not disappear

### Please select the app version

0.5.0

### Please select the Platform / OS Type

Darwin(macOS)

### Please provide your OS version, eg 13.3.1

13.4.1 (c) (22F770820d)

### Please select the OS Arch you are using when encounter the problem

x86_64

**Comment by lisiur** [comment] 2023-07-29 01:53
I can't reproduce this issue locally. Have you clicked the close button? There's a known issue that you can't activate the window by clicking the icon on the dock after closing it. This is an upstream issue:

https://github.com/tauri-apps/tauri/issues/3084

https://github.com/tauri-apps/tao/issues/218

**Comment by normal-coder** [comment] 2023-07-29 03:37
> I can't reproduce this issue locally. Have you clicked the close button? There's a known issue that you can't activate the window by clicking the icon on the dock after closing it. This is an upstream issue:
> 
> [tauri-apps/tauri#3084](https://github.com/tauri-apps/tauri/issues/3084)
> 
> [tauri-apps/tao#218](https://github.com/tauri-apps/tao/issues/218)

I didn't do any extra operations (including Cmd w) other than switching windows normally, which also bothered me. I even tried adding a shortcut to open localhost:23333 , but apparently web-based usage didn't do what I expected.

**Closed** 2024-09-24 01:26 UTC
